#page title
page_title                                : Popcorn Movies                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1400768489                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Trakt client you deserve!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Antoine Barré
your_link                                 : https://twitter.com/Pomanks
your_city                                 : Nantes
email_address                             : contact@popcornmovies.app
facebook_username                         :
instagram_username                        :
twitter_username                          : Pomanks
github_username                           : pomanks
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Manage your lists
    description                           : You can add, remove or update any movie from either your Watchlist, History or Collection.
    fontawesome_icon_name                 : stream

  - title                                 : Stay in sync
    description                           : Wether you perform some action from Trakt.tv or from Popcorn Movies, all the changes will be sync back and forth automatically.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Checkin
    description                           : Watching something? Just perform a Check In and, if enabled, it will automatically create a post on your favorite social networks.
    fontawesome_icon_name                 : play-circle

  - title                                 : Browse
    description                           : Discover tons of new movies.. or search your own. You will never run out of ideas!
    fontawesome_icon_name                 : search

  - title                                 : At a glance
    description                           : Each movie summary opens with a quick access to the more common information but also gives you rich details too.
    fontawesome_icon_name                 : info-circle

  - title                                 : Ready for iOS 13, soon for iOS 14…
    description                           : Supports automatic mode switching (Dark/Light), context menus, rich links, the new modal presentation and so much more! iOS 14 support will come this fall!
    fontawesome_icon_name                 : check

  - title                                 : Dynamic Type
    description                           : Native support for Dynamic Type, the app will always match your own font size!
    fontawesome_icon_name                 : universal-access


  - title                                 : Want more?
    description                           : Send us your ideas to “ideas@popcornmovies.app”.
    fontawesome_icon_name                 : lightbulb

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

#  - title                                 : # New Feature Title
#    description                           : # New Feature Description
#    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#767680"
topbar_transparency                       : 0.18
topbar_title_color                        : "#FFFFFF"

cover_image                               : assets/iron-man.jpg  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black   # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#1C1C1E"

link_color                                : "#FF375F"

app_title_color                           : "#FFFFFF"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#FFFFFF"

feature_title_color                       : "#FFFFFF"
feature_text_color                        : "#EBEBF599"

feature_icons_foreground_color            : "#FF375F"
feature_icons_background_color            : "#7878805C"

social_icons_foreground_color             : "#FF375F"
social_icons_background_color             : "#7878805C"

footer_text_color                         : "#EBEBF54D"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

include:
  - .well-known
  
# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - CHANGELOG.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
