#page title
page_title                                : Popcorn Movies                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1400768489                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Trakt client you deserve!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Antoine Barré
your_link                                 : https://twitter.com/Pomanks
your_city                                 : Nantes
email_address                             : contact@popcornmovies.app
facebook_username                         :
instagram_username                        :
twitter_username                          : Pomanks
github_username                           : pomanks
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : MANAGE YOUR WATCHLIST
    description                           : Your Watchlist is the best way to never forget the movies you’d like to watch!
    fontawesome_icon_name                 : stream

  - title                                 : SEE WHAT’S COMING
    description                           : All upcoming movies are automatically added into the Upcoming list so you know what’s available or not..
    fontawesome_icon_name                 : calendar-alt

  - title                                 : POWERFUL HISTORY
    description                           : You don’t remember having watched a specific movie? Quickly search your History and you’ll know! You’ve watched a movie multiple times? You can add - and delete - as many plays as you want.
    fontawesome_icon_name                 : history

  - title                                 : STAY IN SYNC
    description                           : Every movie you add to your lists will be synchronized to/from your Trakt account, instantly!
    fontawesome_icon_name                 : sync-alt

  - title                                 : CHECKIN / NOW WATCHING
    description                           : Tell others you’re watching some movie with a Checkin and quickly see its informations right from your profile! No more searching for the movie in your list or anywhere else!
    fontawesome_icon_name                 : play-circle

  - title                                 : BROWSE
    description                           : Discover tons of new movies with new suggestions from other Trakt users.. You will never run out of ideas ever again!
    fontawesome_icon_name                 : film

  - title                                 : SEARCH
    description                           : Sometimes you just know what you’re looking for.. The advanced search feature will help you find it in no time! Double tap on the Browse item to activate Quick Search.
    fontawesome_icon_name                 : search

  - title                                 : SHARE
    description                           : You want others to know about an interesting movie? Simply share it with them via AirDrop, iMessage and more!
    fontawesome_icon_name                 : share

  - title                                 : RATINGS
    description                           : Rate your favorite movies right from their page and see how others feel about them too!
    fontawesome_icon_name                 : star

  - title                                 : CHECK YOUR STATS
    description                           : Your profile is the right place to check your last activities and movies stats.. Let’s see how many movies you’ve watched until now!
    fontawesome_icon_name                 : info-circle

  - title                                 : AND MORE TO COME…
    description                           : New features are constantly added over time, stay tuned by following us on Twitter and/or Reddit!
    fontawesome_icon_name                 : ellipsis-h

# Theme Settings
topbar_color                              : "#767680"
topbar_transparency                       : 0.18
topbar_title_color                        : "#FFFFFF"

cover_image                               : assets/iron-man.jpg  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black   # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#1C1C1E"

link_color                                : "#FF375F"

app_title_color                           : "#FFFFFF"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#FFFFFF"

feature_title_color                       : "#FFFFFF"
feature_text_color                        : "#EBEBF599"

feature_icons_foreground_color            : "#FF375F"
feature_icons_background_color            : "#7878805C"

social_icons_foreground_color             : "#FF375F"
social_icons_background_color             : "#7878805C"

footer_text_color                         : "#EBEBF54D"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

include:
  - .well-known
  
# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - CHANGELOG.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
